extern void FreeVariableCarrier(VariableObjCarrier Carrier);
extern void FreeTrainCarrier(TrainObjCarrier Carrier);
extern void FreeVariableLinkMioneObjectCarrierOfWeldFunctionRespondObj(MioneObjCarrier Carrier);