//word define
<word_normal> ::= 'a' | 'A'
         | 'b' | 'B'
         | 'c' | 'C'
         | 'd' | 'D'
         | 'e' | 'E'
         | 'f' | 'F'
         | 'g' | 'G'
         | 'h' | 'H'
         | 'i' | 'I'
         | 'j' | 'J'
         | 'k' | 'K'
         | 'l' | 'L'
         | 'm' | 'M'
         | 'n' | 'N'
         | 'o' | 'O'
         | 'p' | 'P'
         | 'q' | 'Q'
         | 'r' | 'R'
         | 's' | 'S'
         | 't' | 'T'
         | 'u' | 'U'
         | 'v' | 'V'
         | 'w' | 'W'
         | 'x' | 'X'
         | 'y' | 'Y'
         | 'z' | 'Z'
         | '_'
<word_number> ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
<word_body> ::= (<word_normal> | <word_number>) (<word_body> | epsilon)
<word> ::= <word_normal> (<word_body> | epsilon)

//6 types of object
<head> ::= "set" | "if" | "while" | "return"
<prompt> ::= "=" | "then" | "else" | "do"

<symbol_after> ::= "sizeof" | ")"
<symbol_before> ::= "-" | "."
<symbol_both> ::= "-" | "+" | "*" | "/" | "==" | "!=" | "<" | ">" | "<=" | ">=" | "." | "," | "("
<symbol> ::= <symbol_after> | <symbol_before> | <symbol_both>

<variable> ::= <word>

<value_string> ::= ('"' (<word_body> | epsilon) '"') | ("'" (<word_body> | epsilon) "'")
<value_number> ::= <word_number> (<value_number> | epsilon)
<value_function> ::= "function" <trains> "end"
<value_range> ::= "range" <trains> "end"
<value_table> ::= "{" <trains> "}"
<value> ::= <value_string> | <value_number> | <value_function> | <value_range> | <value_table>

<weld> ::= "subject"

//expression define
<expression_resource> ::= ((<symbol_before>) | epsilon) (<value> | <variable> | <weld> <train> (';' | epsilon)) ((<symbol_both> <expression_resource>) | (<symbol_after>) | epsilon)
<expression_container> ::= ((<symbol_before>) | epsilon) (<variable> | <weld> <train> (';' | epsilon)) ((<symbol_both> <expression_container>) | (<symbol_after>) | epsilon)
<expression> ::= <expression_resource> | <expression_container>

//carriage define
<carriage_head> ::= (<head> (epsilon | <expression>)) | <expression>
<carriage_body> ::= (<prompt> (epsilon | <expression>)) | <expression>
<carriage_bodies> ::= <carriage_body> (<carriage_bodies> | epsilon)

//train define
<train> ::= <carriage_head> <carriage_bodies>
<trains> ::= <train> (<trains> | epsilon)

//certain trains
<set_train> ::= "set" <expression_container> ( "=" <expression_resource> | epsilon )

<elif_link> ::= "elif" <expression_resource> "then"
<if_train> ::= "if" <expression_resource> "then" <value_range> ( "else" <value_range> | espilon )